language: node_js
node_js:
- '11'
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: Trevor.Sundberg@gmail.com
  api_key:
    secure: XCRWBW5PxTMvqk9KCcA6GqCy7m1bs72aDaFG2yUDDF90/F3HaQ2McMf6gPaxmec1xe9hqhfl8zl8jMzbEe+IUN+u71mX7LR0vw7WxTWFEn3hhpSxVEogQ0h0lmgcDe3r2wkSkFTU+T/T0I7793fglZwwLrL0Gwv3UaPgwkRAH6DCSwT0yZrZrTpEd5jU1SzA1X8jYM3VOefcreuy89LcrK23wIhPwpcDxZi11qt7goo0o6Z577hXuMx0DME0/fjR4d3z8TUsNlKeYtAZfzBR5ppDQO3P9g2albwIKSdeSMmQi0ZWPi+7QgSMLqBeGjL4ANoTguj1H77X7kk5gSeWt4XDQU3RmXatcP8jJfQba45taO5UKXWppqQNh5iI8SsDYFVDtpYUlXNneYK7i1F1RD1mvaWJBXzjDnqtLS/q6cHL/4lwA6fxLnKmdkznZXItw5nuxwtak8asHIZjM/LLVcJoM+4gR6PnbwB6eAdQ5o5AsCVtYEEc3UbpaBPlFM0FYeaB50978fYRDl6gwXzTjUnP9mNbwdMllhNd4Kp+4U9WDGJdNX8CHkmW+DbqI/M45HZpLEYU6/xHjOKsONkLtbz2FlK7thyYtHxbGAbeTufIwyLN9M0eX7844Q4R6WvEOX/aBtAbfvJPp4jtTqhYJ/eXEzG5dBXvbRMRH2C+IRg=
  on:
    tags: true
    repo: codesweets/core
