language: node_js
node_js:
- '11'
addons:
  apt:
    packages:
      - xvfb
install:
- npm install
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
- npm run build
- npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: Trevor.Sundberg@gmail.com
  api_key:
    secure: xQnjYR/CxQpkM2UD/wTRdWkARFKmo42wUXeaG0wRJa4RRSqBc73TDWVqIorTYET/03vkyWOMLMKDEFg4RQ7vabgRS1RGtDSpSUTNLM3tIKuynIEZTrSy+mS8V4tvGgTsKyWFDnVmIUy/V9a3S95Jo3nsY3o3zkRkIgqBMqwbJuQh4rb0gIQhQVYB/2DKrKMpW8Tym13iPYbEXfv1XQ+zswQQZTHqilbdfmM8Jy/gmzWRJ2JRrfmFGR0mnbH5yM2C4HHfhUgVnsRWwkB0nE2npmwODwGfanJX4yK3A1quIU1PcK2AUHUaQilkvdc4wkmECHEmXyRQ+6k8LA1qVLWaoN7W1aE0pvzhN7eLvKDUsuwc012HXwznomwz5XpOYW4s76l+rrXsmqDpcnjAx8kXXk2uuR3deo1r9kz0AXTzVIQgdr+SJ9F22oLsLcDVN1EP1A7nL3WecRbLOsXcIjmudas5GK2lHuM8td4ASNWhqD7TqwprtI+HiosmPLlKbAPPraso4pKxFiWWXNm4X9QCoyi85fxXEOR9SM7pXQ4DZPj1NpGXOWLy9W6666oeAHcoNXvRm6yzGzDL7CyVo6z3tiWCJeSjO1R+T9H27hXFPmjKFnO0ghZhlwaJJvGBH3hfS7JZWDDI9XICMe97xfqYSxawgINjXyuhI0a97sX9rKg=
  on:
    tags: true
    branch: master
    repo: codesweets/core
