language: node_js
node_js:
- '11'
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: npm
  skip_cleanup: true
  email: Trevor.Sundberg@gmail.com
  api_key:
    secure: i6Ovz0x9/uqNaAlJIN6shB9tGhuJblALUGrSIqRllKt/+q1T2aOc/Q3AM0NIs0rK19XY4GtupujnPyeevZoSlOAGaORE6tBbHnLXsTgWP6WqwYnKls3UP59fN4unl/X1GrvWFWFYP1wxGkwdoJGz9xIVs7PUJBdxjktdhMR+0Ts0b3pfPOjAGETbIF8d8Gxy7xWZbUJL3mFrHhrvoz38zgRvKoEk1k6XJtUYaCe/E0NKwLhz3POH+d0BNgL8ZkkF+W0UHRPJw5WlXmY7+L9Xqn6mO3RJQ+y352VTsPWAx1QATsu72gcd+vgdgxxR1WplSqJPbrorsDnIcbmbNw3XwllJbftjDmoXOL/0fcz9XVXhien16YIQ7hy5PWLpu3sWNUdp28mRaZ9xJwxlp6C4pN6/pmEpJrLVMmI6DychlUf8ygCwbM9CimRxnkHwfga5/e+4TrHP2WgV4n1/bzIdoJZqy0qpJhPLamgwsyM9SD0OqEXsym4Eh/SB9pmvOxyIi+OvRpfpftqlXQ1WOKNnugObGcbkuEeSdy11hczMz+YT6jBwJU/edRQQDgqKLi3WqZ+OB8rEkKc5uF0O/1g+UkJ2VP3QOvh2YmkwMtqfzRy5OkKndGIXgt/iqx1ezE7adFuI3CyYbBDX9rDtzTkPmYBrYx63MOe2hfO954xu3lI=
  on:
    tags: true
    repo: codesweets/core
